name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature') || startsWith(github.head_ref, 'fix') || startsWith(github.head_ref, 'dependabot') }}
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: Install dependencies
        run: npm install
      # - name: Linting
      #   run: npm run lint # Not working due to ts config issues
      - name: Linting
        run: npm run format -- --check
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - lint
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: Install dependencies
        run: npm install
      - name: Run Unit Tests
        run: node --help
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
